#dynamic_title = true

[colors.primary]
background = "#1c1917"
foreground = "#fbeeec"

[env]
TERM = "xterm-256color"

[font]
size = 12.0
offset.y = 2

[font.normal]
family = "Fira Code"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
save_to_clipboard = false

[shell]
program = "/bin/bash"

[window]
decorations = "none"
opacity = 0.95
padding.x = 10
padding.y = 10
